{% set version = "0.9.14" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fstcore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fstcore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fstcore/fstcore_{{ version }}.tar.gz
  sha256: d08efa06003bd65bf5131e17980904c1334afbd7474b09a841effa6810251356

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - _openmp_mutex  # [linux]
    - llvm-openmp  # [osx]
    - lz4-c
    - zstd
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - lz4-c
    - zstd

test:
  commands:
    - $R -e "library('fstcore')"           # [not win]
    - "\"%R%\" -e \"library('fstcore')\""  # [win]

about:
  home: https://www.fstpackage.org/fstcore/
  license: MPL-2.0
  summary: The 'fstlib' library provides multithreaded serialization of compressed data frames using the 'fst' format. The 'fst' format allows for random access of stored data and compression with the 'LZ4' and 'ZSTD' compressors.
  license_family: OTHER
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
